services:
  frontend:
    build:
      context: /home/lexun/work/KWORK/filippenkov_artem/training_generator/frontend
      dockerfile: Dockerfile.dev
    container_name: training-generator-frontend
    ports:
      - "5173:5173"
    volumes:
      - /home/lexun/work/KWORK/filippenkov_artem/training_generator/frontend:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - VITE_S3_ENDPOINT=${VITE_S3_ENDPOINT:-https://storage.sh3.su}
      - VITE_S3_BUCKET=${VITE_S3_BUCKET:-training-diagrams}
      - VITE_S3_ACCESS_KEY=${VITE_S3_ACCESS_KEY}
      - VITE_S3_SECRET_KEY=${VITE_S3_SECRET_KEY}
      - VITE_S3_REGION=${VITE_S3_REGION:-us-east-1}
    stdin_open: true
    tty: true

volumes:
  node_modules: